### ISSUE TITLE
报错太多了呜呜呜

### ISSUE THREAD

**Issue by xixiaaaa** [lanjiangyu/-#1]
C:\Users\XIXIA\AppData\Local\Programs\Python\Python39\python.exe C:/Users/XIXIA/OneDrive/桌面/--main/entry.py
Image shape (844, 450, 3)
Traceback (most recent call last):
  File "C:\Users\XIXIA\AppData\Local\Programs\Python\Python39\lib\site-packages\pytesseract\pytesseract.py", line 255, in run_tesseract
    proc = subprocess.Popen(cmd_args, **subprocess_args())
  File "C:\Users\XIXIA\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\XIXIA\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 1420, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] 系统找不到指定的文件。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\XIXIA\OneDrive\桌面\--main\entry.py", line 4, in <module>
    start()
  File "C:\Users\XIXIA\OneDrive\桌面\--main\nursery\__init__.py", line 8, in start
    chessboard = ocr()
  File "C:\Users\XIXIA\OneDrive\桌面\--main\nursery\modules\ocr.py", line 84, in ocr
    numbers = pytesseract.image_to_string(
  File "C:\Users\XIXIA\AppData\Local\Programs\Python\Python39\lib\site-packages\pytesseract\pytesseract.py", line 423, in image_to_string
    return {
  File "C:\Users\XIXIA\AppData\Local\Programs\Python\Python39\lib\site-packages\pytesseract\pytesseract.py", line 426, in <lambda>
    Output.STRING: lambda: run_and_get_output(*args),
  File "C:\Users\XIXIA\AppData\Local\Programs\Python\Python39\lib\site-packages\pytesseract\pytesseract.py", line 288, in run_and_get_output
    run_tesseract(**kwargs)
  File "C:\Users\XIXIA\AppData\Local\Programs\Python\Python39\lib\site-packages\pytesseract\pytesseract.py", line 260, in run_tesseract
    raise TesseractNotFoundError()
pytesseract.pytesseract.TesseractNotFoundError: E:\enviroument\tesseract.exe is not installed or it's not in your PATH. See README file for more information.

进程已结束，退出代码为 1

**Comment by xuxiaohu6** [comment]
/nursery/modules/ocr.py第83行，把 E:\enviroument\tesseract.exe改成你自己的安装地址，默认是   r'C:\Program Files\Tesseract-OCR\tesseract.exe'
